import 'package:flutter/material.dart';
import 'package:grid_view/app_model.dart';

final List<AppModel> appList = [
  AppModel(
    appIcon: const Icon(Icons.abc, color: Colors.blue),
    appName: "Tigcik",
    releaseDate: DateTime(2026, 02, 16),
    appCategory: "Eğitim / El Sanatları",
    storeUrl: "https://github.com/KorayTemizkan/tigcik",
  ),
  AppModel(
    appIcon: const Icon(Icons.directions_bus, color: Colors.orange),
    appName: "Titanic Tracker",
    releaseDate: DateTime(1912, 04, 10),
    appCategory: "Seyahat",
    storeUrl: "https://store.titanic.com",
  ),
  AppModel(
    appIcon: const Icon(Icons.code, color: Colors.green),
    appName: "Dart Master",
    releaseDate: DateTime(2025, 12, 01),
    appCategory: "Geliştirici Araçları",
    storeUrl: "https://pub.dev",
  ),
  AppModel(
    appIcon: const Icon(Icons.brush, color: Colors.pink),
    appName: "Designly",
    releaseDate: DateTime(2026, 01, 20),
    appCategory: "Tasarım",
    storeUrl: "https://figma.com",
  ),
  AppModel(
    appIcon: const Icon(Icons.fitness_center, color: Colors.red),
    appName: "FitFlow",
    releaseDate: DateTime(2024, 05, 15),
    appCategory: "Sağlık",
    storeUrl: "https://fitflow.app",
  ),
  AppModel(
    appIcon: const Icon(Icons.fastfood, color: Colors.yellow),
    appName: "QuickBite",
    releaseDate: DateTime(2025, 08, 12),
    appCategory: "Yiyecek & İçecek",
    storeUrl: "https://quickbite.com",
  ),
  AppModel(
    appIcon: const Icon(Icons.music_note, color: Colors.purple),
    appName: "MelodyHub",
    releaseDate: DateTime(2023, 11, 30),
    appCategory: "Müzik",
    storeUrl: "https://spotify.com",
  ),
  AppModel(
    appIcon: const Icon(Icons.camera_alt, color: Colors.teal),
    appName: "SnapPerfect",
    releaseDate: DateTime(2025, 03, 05),
    appCategory: "Fotoğrafçılık",
    storeUrl: "https://snap.app",
  ),
  AppModel(
    appIcon: const Icon(Icons.account_balance_wallet, color: Colors.indigo),
    appName: "CoinTrack",
    releaseDate: DateTime(2026, 02, 01),
    appCategory: "Finans",
    storeUrl: "https://cointrack.io",
  ),
  AppModel(
    appIcon: const Icon(Icons.gamepad, color: Colors.deepOrange),
    appName: "PixelQuest",
    releaseDate: DateTime(2024, 09, 22),
    appCategory: "Oyun",
    storeUrl: "https://pixelquest.game",
  ),
  AppModel(
    appIcon: const Icon(Icons.abc, color: Colors.blue),
    appName: "Tigcik",
    releaseDate: DateTime(2026, 02, 16),
    appCategory: "Eğitim / El Sanatları",
    storeUrl: "https://github.com/KorayTemizkan/tigcik",
  ),
  AppModel(
    appIcon: const Icon(Icons.directions_bus, color: Colors.orange),
    appName: "Titanic Tracker",
    releaseDate: DateTime(1912, 04, 10),
    appCategory: "Seyahat",
    storeUrl: "https://store.titanic.com",
  ),
  AppModel(
    appIcon: const Icon(Icons.code, color: Colors.green),
    appName: "Dart Master",
    releaseDate: DateTime(2025, 12, 01),
    appCategory: "Geliştirici Araçları",
    storeUrl: "https://pub.dev",
  ),
  AppModel(
    appIcon: const Icon(Icons.brush, color: Colors.pink),
    appName: "Designly",
    releaseDate: DateTime(2026, 01, 20),
    appCategory: "Tasarım",
    storeUrl: "https://figma.com",
  ),
  AppModel(
    appIcon: const Icon(Icons.fitness_center, color: Colors.red),
    appName: "FitFlow",
    releaseDate: DateTime(2024, 05, 15),
    appCategory: "Sağlık",
    storeUrl: "https://fitflow.app",
  ),
  AppModel(
    appIcon: const Icon(Icons.fastfood, color: Colors.yellow),
    appName: "QuickBite",
    releaseDate: DateTime(2025, 08, 12),
    appCategory: "Yiyecek & İçecek",
    storeUrl: "https://quickbite.com",
  ),
  AppModel(
    appIcon: const Icon(Icons.music_note, color: Colors.purple),
    appName: "MelodyHub",
    releaseDate: DateTime(2023, 11, 30),
    appCategory: "Müzik",
    storeUrl: "https://spotify.com",
  ),
  AppModel(
    appIcon: const Icon(Icons.camera_alt, color: Colors.teal),
    appName: "SnapPerfect",
    releaseDate: DateTime(2025, 03, 05),
    appCategory: "Fotoğrafçılık",
    storeUrl: "https://snap.app",
  ),
  AppModel(
    appIcon: const Icon(Icons.account_balance_wallet, color: Colors.indigo),
    appName: "CoinTrack",
    releaseDate: DateTime(2026, 02, 01),
    appCategory: "Finans",
    storeUrl: "https://cointrack.io",
  ),
  AppModel(
    appIcon: const Icon(Icons.gamepad, color: Colors.deepOrange),
    appName: "PixelQuest",
    releaseDate: DateTime(2024, 09, 22),
    appCategory: "Oyun",
    storeUrl: "https://pixelquest.game",
  ),
];
