// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'coral_fragment_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6002376162787354356),
    name: 'CoralFragmentModel',
    lastPropertyId: const obx_int.IdUid(6, 6166694801566032348),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8958921634665318279),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8100731154255289521),
        name: 'title',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 2127700252981651399),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6086563074702462274),
        name: 'species',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7327838053252550999),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 880989732324049578),
        name: 'fragmentDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6166694801566032348),
        name: 'isAncient',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6002376162787354356),
    lastIndexId: const obx_int.IdUid(1, 2127700252981651399),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CoralFragmentModel: obx_int.EntityDefinition<CoralFragmentModel>(
      model: _entities[0],
      toOneRelations: (CoralFragmentModel object) => [],
      toManyRelations: (CoralFragmentModel object) => {},
      getId: (CoralFragmentModel object) => object.id,
      setId: (CoralFragmentModel object, int id) {
        object.id = id;
      },
      objectToFB: (CoralFragmentModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final speciesOffset = fbb.writeString(object.species);
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, speciesOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addInt64(4, object.fragmentDate.millisecondsSinceEpoch);
        fbb.addBool(5, object.isAncient);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final speciesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final fragmentDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isAncientParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = CoralFragmentModel(
          id: idParam,
          title: titleParam,
          species: speciesParam,
          content: contentParam,
          fragmentDate: fragmentDateParam,
          isAncient: isAncientParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CoralFragmentModel] entity fields to define ObjectBox queries.
class CoralFragmentModel_ {
  /// See [CoralFragmentModel.id].
  static final id = obx.QueryIntegerProperty<CoralFragmentModel>(
    _entities[0].properties[0],
  );

  /// See [CoralFragmentModel.title].
  static final title = obx.QueryStringProperty<CoralFragmentModel>(
    _entities[0].properties[1],
  );

  /// See [CoralFragmentModel.species].
  static final species = obx.QueryStringProperty<CoralFragmentModel>(
    _entities[0].properties[2],
  );

  /// See [CoralFragmentModel.content].
  static final content = obx.QueryStringProperty<CoralFragmentModel>(
    _entities[0].properties[3],
  );

  /// See [CoralFragmentModel.fragmentDate].
  static final fragmentDate = obx.QueryDateProperty<CoralFragmentModel>(
    _entities[0].properties[4],
  );

  /// See [CoralFragmentModel.isAncient].
  static final isAncient = obx.QueryBooleanProperty<CoralFragmentModel>(
    _entities[0].properties[5],
  );
}
